// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhvgtC0ccsVK4cRdOmPHJcbczU04HT1qI',
    appId: '1:514423062513:web:70ecaccb3c8c1c2a508e50',
    messagingSenderId: '514423062513',
    projectId: 'cmsc23-todo-app-lblaserna',
    authDomain: 'cmsc23-todo-app-lblaserna.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-lblaserna.appspot.com',
    measurementId: 'G-2G2CCRTK1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVy8QVTJk2RrokvZe4p7dic-lmzGFri-0',
    appId: '1:514423062513:android:06744bc969b401e1508e50',
    messagingSenderId: '514423062513',
    projectId: 'cmsc23-todo-app-lblaserna',
    storageBucket: 'cmsc23-todo-app-lblaserna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8lUq5HyLc6zMi2eQUJAsh2U-H549Hw3g',
    appId: '1:514423062513:ios:98350b1c69bfb315508e50',
    messagingSenderId: '514423062513',
    projectId: 'cmsc23-todo-app-lblaserna',
    storageBucket: 'cmsc23-todo-app-lblaserna.appspot.com',
    iosBundleId: 'com.example.week9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8lUq5HyLc6zMi2eQUJAsh2U-H549Hw3g',
    appId: '1:514423062513:ios:98350b1c69bfb315508e50',
    messagingSenderId: '514423062513',
    projectId: 'cmsc23-todo-app-lblaserna',
    storageBucket: 'cmsc23-todo-app-lblaserna.appspot.com',
    iosBundleId: 'com.example.week9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhvgtC0ccsVK4cRdOmPHJcbczU04HT1qI',
    appId: '1:514423062513:web:6ee645d36a2c50ec508e50',
    messagingSenderId: '514423062513',
    projectId: 'cmsc23-todo-app-lblaserna',
    authDomain: 'cmsc23-todo-app-lblaserna.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-lblaserna.appspot.com',
    measurementId: 'G-RSK1PNC1CW',
  );

}